"""
PhotoScore Database — Supabase (PostgreSQL) Implementation.

Connects to Supabase to handle 5,000+ concurrent users seamlessly.

IMPORTANT: Run this SQL in your Supabase SQL Editor to create the tables:

CREATE TABLE users (
    phone_number TEXT PRIMARY KEY,
    language TEXT DEFAULT 'en',
    marketplace TEXT DEFAULT 'amazon',
    is_paid BOOLEAN DEFAULT FALSE,
    paid_until TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_active TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number TEXT NOT NULL REFERENCES users(phone_number),
    used_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    score INTEGER DEFAULT 0
);
"""

import os
import logging
from datetime import datetime, date
from supabase import create_client, Client

logger = logging.getLogger(__name__)

SUPABASE_URL = os.environ.get("SUPABASE_URL", "")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY", "")
FREE_DAILY_LIMIT = 5

def get_supabase() -> Client:
    if not SUPABASE_URL or not SUPABASE_KEY:
        raise ValueError("SUPABASE_URL and SUPABASE_KEY must be set in .env")
    return create_client(SUPABASE_URL, SUPABASE_KEY)

def init_db():
    """Verify Supabase connection on startup."""
    try:
        supabase = get_supabase()
        # Ping the DB by fetching 1 user
        supabase.table("users").select("phone_number").limit(1).execute()
        logger.info("Connected to Supabase PostgreSQL ✅")
    except Exception as e:
        logger.error(f"Supabase connection failed: {e}")
        logger.error("Please ensure your SUPABASE_URL and SUPABASE_KEY are correct, and tables are created.")

# ─────────────────────────────────────────────
# USER MANAGEMENT
# ─────────────────────────────────────────────

def get_or_create_user(phone: str) -> dict:
    """Get existing user or create new one in Supabase."""
    supabase = get_supabase()
    
    # 1. Try to fetch user
    response = supabase.table("users").select("*").eq("phone_number", phone).execute()
    
    if len(response.data) > 0:
        # Update last active
        supabase.table("users").update({"last_active": datetime.now().isoformat()}).eq("phone_number", phone).execute()
        return response.data[0]
    
    # 2. If not exists, insert new user
    new_user = {
        "phone_number": phone,
        "language": "en",
        "marketplace": "amazon",
        "is_paid": False,
        "paid_until": None
    }
    response = supabase.table("users").insert(new_user).execute()
    return response.data[0]

def set_user_language(phone: str, lang: str):
    supabase = get_supabase()
    supabase.table("users").update({"language": lang}).eq("phone_number", phone).execute()

def set_user_marketplace(phone: str, marketplace: str):
    supabase = get_supabase()
    supabase.table("users").update({"marketplace": marketplace}).eq("phone_number", phone).execute()

def set_user_paid(phone: str, paid_until: str):
    supabase = get_supabase()
    supabase.table("users").update({"is_paid": True, "paid_until": paid_until}).eq("phone_number", phone).execute()

# ─────────────────────────────────────────────
# USAGE TRACKING
# ─────────────────────────────────────────────

def record_usage(phone: str, score: int = 0):
    supabase = get_supabase()
    supabase.table("usage").insert({"phone_number": phone, "score": score}).execute()

def get_daily_usage(phone: str) -> int:
    supabase = get_supabase()
    today = date.today().isoformat()
    
    # In Supabase REST API, filtering by exact date function requires some tricks,
    # so we filter by >= start of day
    start_of_day = f"{today}T00:00:00Z"
    
    # Fetch count using select method
    response = supabase.table("usage").select("id", count="exact").eq("phone_number", phone).gte("used_at", start_of_day).execute()
    return response.count if response.count is not None else 0

def get_remaining_checks(phone: str) -> tuple[int, int]:
    user = get_or_create_user(phone)

    # Paid users get unlimited
    if user.get("is_paid"):
        if user.get("paid_until"):
            paid_until = datetime.fromisoformat(user["paid_until"].replace("Z", "+00:00"))
            if paid_until.timestamp() > datetime.now().timestamp():
                return (999, 999)  # Unlimited
            else:
                # Subscription expired
                supabase = get_supabase()
                supabase.table("users").update({"is_paid": False}).eq("phone_number", phone).execute()

    used = get_daily_usage(phone)
    remaining = max(0, FREE_DAILY_LIMIT - used)
    return (remaining, FREE_DAILY_LIMIT)

def can_check(phone: str) -> bool:
    remaining, _ = get_remaining_checks(phone)
    return remaining > 0

# ─────────────────────────────────────────────
# STATS
# ─────────────────────────────────────────────

def get_total_users() -> int:
    supabase = get_supabase()
    resp = supabase.table("users").select("phone_number", count="exact").execute()
    return resp.count if resp.count is not None else 0

def get_total_checks() -> int:
    supabase = get_supabase()
    resp = supabase.table("usage").select("id", count="exact").execute()
    return resp.count if resp.count is not None else 0

def get_paid_users() -> int:
    supabase = get_supabase()
    resp = supabase.table("users").select("phone_number", count="exact").eq("is_paid", True).execute()
    return resp.count if resp.count is not None else 0
