"""
PhotoScore Database — Supabase (PostgreSQL) Implementation.

Connects to Supabase to handle 5,000+ concurrent users seamlessly.

IMPORTANT: Run this SQL in your Supabase SQL Editor to create the tables:

CREATE TABLE users (
    phone_number TEXT PRIMARY KEY,
    language TEXT,
    marketplace TEXT DEFAULT 'amazon',
    is_paid BOOLEAN DEFAULT FALSE,
    paid_until TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_active TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number TEXT NOT NULL REFERENCES users(phone_number),
    used_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    score INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS processed_events (
    id TEXT PRIMARY KEY,
    processed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE processed_events ENABLE ROW LEVEL SECURITY;

-- Optional: Add this to pg_cron to clean up the dedupe table so it doesn't grow infinitely
-- SELECT cron.schedule('cleanup_events', '0 0 * * *', $$DELETE FROM processed_events WHERE processed_at < NOW() - INTERVAL '7 days'$$);
"""

import os
import logging
from datetime import datetime, date, timezone
from supabase import create_client, Client
from postgrest.exceptions import APIError

logger = logging.getLogger(__name__)

SUPABASE_URL = os.environ.get("SUPABASE_URL", "")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY", "")
FREE_DAILY_LIMIT = 5

_client: Client | None = None

def get_supabase() -> Client:
    global _client
    if _client is None:
        if not SUPABASE_URL or not SUPABASE_KEY:
            raise ValueError("SUPABASE_URL and SUPABASE_KEY must be set in .env")
        _client = create_client(SUPABASE_URL, SUPABASE_KEY)
    return _client

def init_db():
    """Verify Supabase connection on startup."""
    try:
        supabase = get_supabase()
        # Ping the DB by fetching 1 user
        supabase.table("users").select("phone_number").limit(1).execute()
        logger.info("Connected to Supabase PostgreSQL ✅")
    except Exception as e:
        logger.error(f"Supabase connection failed: {e}")
        logger.error("Please ensure your SUPABASE_URL and SUPABASE_KEY are correct, and tables are created.")
        raise e

# ─────────────────────────────────────────────
# USER MANAGEMENT
# ─────────────────────────────────────────────

def get_or_create_user(phone: str) -> dict:
    """Get existing user or create new one in Supabase."""
    supabase = get_supabase()
    
    # 1. First fetch to check if we already have the language/marketplace defaults set
    response = supabase.table("users").select("*").eq("phone_number", phone).execute()
    if len(response.data) > 0:
        # Atomic update of last_active
        supabase.table("users").update({"last_active": datetime.now(timezone.utc).isoformat()}).eq("phone_number", phone).execute()
        return response.data[0]
    
    # 2. Atomic upsert for new user to avoid race conditions
    response = supabase.table("users").upsert(
        {
            "phone_number": phone,
            "last_active": datetime.now(timezone.utc).isoformat(),
        },
        on_conflict="phone_number",
    ).execute()
    return response.data[0]

def set_user_language(phone: str, lang: str):
    supabase = get_supabase()
    supabase.table("users").update({"language": lang}).eq("phone_number", phone).execute()

def set_user_marketplace(phone: str, marketplace: str):
    supabase = get_supabase()
    supabase.table("users").update({"marketplace": marketplace}).eq("phone_number", phone).execute()

def apply_payment_rpc(dedupe_key: str, phone: str, days: int = 30) -> str | None:
    """Atomic payment processor via Postgres. Returns new paid_until or None if duplicate."""
    supabase = get_supabase()
    resp = supabase.rpc(
        "apply_payment",
        {"p_key": dedupe_key, "p_phone": phone, "p_days": days}
    ).execute()
    return resp.data

# ─────────────────────────────────────────────
# USAGE TRACKING (Atomic RPC)
# ─────────────────────────────────────────────

def consume_check_rpc(phone: str) -> int | None:
    """Atomic quota check via Postgres function. Returns usage ID if allowed."""
    supabase = get_supabase()
    today = date.today().isoformat()
    start_of_day = f"{today}T00:00:00Z"
    
    resp = supabase.rpc(
        "consume_check", 
        {"p_phone": phone, "p_limit": FREE_DAILY_LIMIT, "p_day_start": start_of_day}
    ).execute()
    return resp.data

def update_usage_score(usage_id: int, score: int):
    """Updates the usage row with the final cv score."""
    supabase = get_supabase()
    supabase.table("usage").update({"score": score}).eq("id", usage_id).execute()

# Retaining these purely for display in the /stats or other logic if needed
def get_daily_usage(phone: str) -> int:
    supabase = get_supabase()
    today = date.today().isoformat()
    start_of_day = f"{today}T00:00:00Z"
    response = supabase.table("usage").select("id", count="exact").eq("phone_number", phone).gte("used_at", start_of_day).execute()
    return response.count if response.count is not None else 0

def get_remaining_checks(phone: str) -> tuple[int, int]:
    user = get_or_create_user(phone)
    if user.get("is_paid") and user.get("paid_until"):
        paid_until = datetime.fromisoformat(user["paid_until"].replace("Z", "+00:00"))
        if paid_until.timestamp() > datetime.now(timezone.utc).timestamp():
            return (999, 999)
    used = get_daily_usage(phone)
    return (max(0, FREE_DAILY_LIMIT - used), FREE_DAILY_LIMIT)

# ─────────────────────────────────────────────
# STATS
# ─────────────────────────────────────────────

def get_total_users() -> int:
    supabase = get_supabase()
    resp = supabase.table("users").select("phone_number", count="exact").execute()
    return resp.count if resp.count is not None else 0

def get_total_checks() -> int:
    supabase = get_supabase()
    resp = supabase.table("usage").select("id", count="exact").execute()
    return resp.count if resp.count is not None else 0

def get_paid_users() -> int:
    supabase = get_supabase()
    resp = supabase.table("users").select("phone_number", count="exact").eq("is_paid", True).execute()
    return resp.count if resp.count is not None else 0

# ─────────────────────────────────────────────
# DEDUPLICATION
# ─────────────────────────────────────────────

def claim_event(event_id: str) -> bool:
    """
    Returns True if the event was successfully claimed (not seen before).
    Returns False if the event was already processed (unique violation).
    Raises exception on actual DB errors.
    """
    try:
        supabase = get_supabase()
        supabase.table("processed_events").insert({"id": event_id}).execute()
        return True
    except APIError as e:
        if e.code == "23505":  # unique violation
            return False
        raise

def release_event(event_id: str):
    """Releases the claim on an event if processing fails."""
    supabase = get_supabase()
    supabase.table("processed_events").delete().eq("id", event_id).execute()
